package com.tony.appbooster.data.repository

import com.tony.appbooster.BuildConfig
import com.tony.appbooster.domain.model.common.AppInfo
import com.tony.appbooster.domain.model.common.Resource
import com.tony.appbooster.domain.repository.AppInfoRepository
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Data layer implementation of [AppInfoRepository] that exposes application
 * metadata generated by Gradle as a domain-level [Resource].
 *
 * This repository isolates Android framework dependencies from the domain
 * while providing the current version name and code for display in Settings
 * or about screens.
 *
 */
@Singleton
class AppInfoRepositoryImpl @Inject constructor() : AppInfoRepository {

    /**
     * Loads the version name and version code embedded in the executing APK.
     *
     * @return [Resource.Success] containing the current [AppInfo].
     */
    override suspend fun getAppInfo(): Resource<AppInfo> {
        return Resource.Success(
            AppInfo(
                versionName = BuildConfig.VERSION_NAME,
                versionCode = BuildConfig.VERSION_CODE.toString()
            )
        )
    }
}
