package com.tony.appbooster.domain.model.telemetry

data class OptimizationStepTelemetry(
    val id: Long,
    val runId: Long,
    val stepIndex: Int,
    val totalSteps: Int,
    val packageName: String,
    val modeKey: String,
    val forceOptimize: Boolean,
    val status: String,
    val outcome: OptimizationStepOutcome?,
    val requestedFilter: String?,
    val beforeFilter: String?,
    val afterFilter: String?,
    val artStatus: String?,
    val artFinalStatus: String?,
    val artSizeBytes: Long?,
    val artSizeBeforeBytes: Long?,
    val androidBuild: String?,
    val artModuleVersion: String?,
    val packageLastUpdateTimeMs: Long?,
    val stableOsAdjusted: Boolean,
    val exitCode: Int?,
    val stdout: String?,
    val stderr: String?,
    val displayCommand: String?,
    val durationMs: Long?,
    val storageBefore: StorageSnapshot?,
    val storageAfter: StorageSnapshot?,
    val verificationSource: String?,
    val createdAtMs: Long,
    val updatedAtMs: Long
)
